name: UVB-76 BOT

on:
  schedule:
    - cron: "4 */6 * * *"  # Toutes les 6 heures
  workflow_dispatch:       # Permet de déclencher manuellement ce workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install discord.py selenium webdriver-manager
        pip install pynacl
        sudo apt update
        sudo apt install ffmpeg
        sudo apt update
        sudo apt install pulseaudio
        pip install Flask discord.py discord.py[voice]
        pip install aiohttp
        
    - name: Run Discord Bot
      env:
        DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      run: |
        python bot.py
